#!/bin/bash

cs="${1,,}"

OGBar=$(sed -n 11p ~/.config/qtile/settings/screens.py)
FILE=~/.config/qtile/settings/themes/$cs.py

if [ -f "$FILE" ]; then
	cat ~/.config/qtile/settings/themes/$cs.py > ~/.config/qtile/settings/widgets.py
	echo "Theme changed"
else 
    echo "The list of available themes are:"
    ls ~/.config/qtile/settings/themes/ | sed -e 's/__pycache__//' -e 's/.py/ /' | grep "\S"
fi

### Cyberpunk

CPBar='     return bar.Bar(widgets, 25, opacity=1,background="#00000000")'

if [ $cs = "cyberpunk" ]; then
	feh --bg-fill ~/Wallpapers/city.jpg &
	sed -i "s/$OGBar/$CPBar/" ~/.config/qtile/settings/screens.py
fi

### Gruvbox

GBBar='     return bar.Bar(widgets, 30, opacity=1,background="#282120")'

if [ $cs = "gruvbox" ]; then
	feh --bg-fill ~/Wallpapers/GruvBox.png &
	sed -i "s/$OGBar/$GBBar/" ~/.config/qtile/settings/screens.py
fi



# Config reload

if [ -f "$FILE" ]; then
	qtile cmd-obj -o cmd -f reload_config
fi
