#!/bin/bash

th="${1,,}"

OGBar=$(sed -n 11p ~/.config/qtile/settings/screens.py)
FILE=~/.config/qtile/settings/themes/$th.py

rand () {
	echo $(shuf -i 0-$1 -n1)
}

if [ -f "$FILE" ]; then
	cat ~/.config/qtile/settings/themes/$th.py > ~/.config/qtile/settings/widgets.py
	echo "Theme changed"
else 
    echo "The list of available themes are:"
    ls ~/.config/qtile/settings/themes/ | sed -e 's/__pycache__//' -e 's/.py/ /' | grep "\S"
fi

### Gruvbox

GBBar='     return bar.Bar(widgets, 30, opacity=1,background="#282120")'


bgsGB=($(ls ~/Wallpapers/GruvBox))

BG=${bgsGB[$(rand ${#bgsGB[@]})]}

if [ $th = "gruvbox" ]; then
	feh --bg-fill ~/Wallpapers/GruvBox/$BG &
	sed -i "s/$OGBar/$GBBar/" ~/.config/qtile/settings/screens.py
fi

### CyberPunk

CPBar='     return bar.Bar(widgets, 25, opacity=1,background="#00000000")'

bgsCP=($(ls ~/Wallpapers/CyberPunk))

BG=${bgsCP[$(rand ${#bgsCP[@]})]}

if [ $th = "cyberpunk" ]; then
	feh --bg-fill ~/Wallpapers/CyberPunk/$BG &
	sed -i "s/$OGBar/$CPBar/" ~/.config/qtile/settings/screens.py
fi


### BNW

BNWBar='     return bar.Bar(widgets, 25, opacity=1,background="#FFFFFF")'

bgsBNW=($(ls ~/Wallpapers/BNW))

BG=${bgsBNW[$(rand ${#bgsBNW[@]})]}


if [ $th = "bnw" ]; then
	feh --bg-fill ~/Wallpapers/BNW/$BG &
	sed -i "s/$OGBar/$BNWBar/" ~/.config/qtile/settings/screens.py
fi



# Config reload

if [ -f "$FILE" ]; then
	qtile cmd-obj -o cmd -f reload_config
fi
